import { Amplify } from 'aws-amplify';

/**
 * Loads Amplify configuration from environment variables or from the default config for development
 */
export const loadAmplifyConfig = (): any => {
  // Try to load the configuration generated by Amplify during deployment
  try {
    // In production, this file would be generated during build time
    // For development, we use a default configuration
    if (process.env.NODE_ENV === 'production' && typeof process.env.AMPLIFY_CONFIG === 'string') {
      return JSON.parse(process.env.AMPLIFY_CONFIG);
    }
  } catch (error) {
    console.warn('Error loading Amplify configuration:', error);
  }
  
  // Default configuration for development
  return {
    Auth: {
      Cognito: {
        userPoolId: process.env.COGNITO_USER_POOL_ID || 'dummy-user-pool-id',
        userPoolClientId: process.env.COGNITO_USER_POOL_CLIENT_ID || 'dummy-client-id',
        identityPoolId: process.env.COGNITO_IDENTITY_POOL_ID || 'dummy-identity-pool-id',
        signUpVerificationMethod: 'code',
      }
    },
    API: {
      REST: {
        cryptoApi: {
          endpoint: process.env.API_ENDPOINT || 'https://api.example.com',
        }
      }
    }
  };
}; 